/* Showing results for Tb_Campanha.xlsx */

/* CREATE TABLE */
CREATE TABLE TB_CAMPANHA(
ID_CAMPANHA INT NOT NULL PRIMARY KEY,
NOME_CAMPANHA VARCHAR(100),
FATOR_CONVERSAO DECIMAL(8,2),
STATUS VARCHAR(100),
TIPO_FRETE VARCHAR(100),
SEGMENTO_CLIENTE VARCHAR(100)
);

/* INSERT QUERY NO: 1 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
1, 'Padrão', 1, 'ATIVO', 'CLIENTE', 'VARIEDADES'
);

/* INSERT QUERY NO: 2 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
10095, 'Programa Nestle', 1.03626943, 'INATIVO', 'CLIENTE', 'ALIMENTOS'
);

/* INSERT QUERY NO: 3 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
40226, 'Rede Natura', 10, 'ATIVO', 'CAMPANHA', 'BELEZA'
);

/* INSERT QUERY NO: 4 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
40362, 'Clube LG 1 x 1', 1, 'ATIVO', 'CLIENTE', 'ELETRONICOS'
);

/* INSERT QUERY NO: 5 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
40367, 'Cielo Fidelidade', 232.5581395, 'INATIVO', 'CLIENTE', 'FINANCEIRO'
);

/* INSERT QUERY NO: 6 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
40391, 'Vivo B2B', 0.200803213, 'ATIVO', 'CAMPANHA', 'TELEFONIA'
);

/* INSERT QUERY NO: 7 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
40430, 'Diageo Experience', 1, 'INATIVO', 'CLIENTE', 'BEBIDAS'
);

/* INSERT QUERY NO: 8 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
40515, 'Meu Mundo Avon', 142.8571429, 'ATIVO', 'CAMPANHA', 'BELEZA'
);

/* INSERT QUERY NO: 9 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
40520, 'Votorantin Somos Mais', 232.5581395, 'ATIVO', 'CAMPANHA', 'CONSTRUÇÃO'
);

/* INSERT QUERY NO: 10 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
50556, 'Fast Shop Méliuz', 1, 'INATIVO', 'CLIENTE', 'VARIEDADES'
);

/* INSERT QUERY NO: 11 */
INSERT INTO TB_CAMPANHA(ID_CAMPANHA, NOME_CAMPANHA, FATOR_CONVERSAO, STATUS, TIPO_FRETE, SEGMENTO_CLIENTE)
VALUES
(
50578, 'Suvinil Sou Mais', 54.054054, 'ATIVO', 'CAMPANHA', 'CONSTRUÇÃO'
);