/* Showing results for Tb_Loja.xlsx */

/* CREATE TABLE */
CREATE TABLE TB_LOJA(
ID_LOJA VARCHAR(100),
ID_PARCEIRO VARCHAR(100),
ID_CAMPANHA VARCHAR(100),
NOME_LOJA VARCHAR(100),
VIVISEL VARCHAR(100),
STATUS_LOJA VARCHAR(100)
);